name: currency_converter
description: A small flutter currency converter app using updated rates.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: "2.10.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  currency_pickers: ^1.0.6

  bloc: ^6.0.3
  flutter_bloc: ^6.0.5

  auto_size_text: ^2.1.0

  http: ^0.12.2

  sqflite: ^1.3.1+1
  path_provider: ^1.6.18


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0
  flutter_launcher_icons: ^0.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

flutter_icons:
  image_path: 'assets/images/logo.png'
  android: true
  ios: true